import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

/** Cache only the application shell and files generated by this build. */
function publicShellWorker(): Plugin {
  return {
    name: 'family-public-shell-worker',
    enforce: 'post' as const,
    generateBundle(_options, bundle) {
      const buildFiles = Object.keys(bundle).filter((name) => /\.(?:js|css|woff2?)$/.test(name));
      const files = [
        'index.html',
        'manifest.webmanifest',
        'favicon.svg',
        'nasza-rodzina-logo.svg',
        'icons/icon.svg',
        'icons/icon-192.png',
        'icons/icon-512.png',
        'icons/apple-touch-icon.png',
        ...buildFiles,
      ];
      const digest = createHash('sha256');
      for (const entry of Object.values(bundle)) digest.update(entry.type === 'chunk' ? entry.code : entry.source);
      for (const file of files.filter((name) => name !== 'index.html' && !buildFiles.includes(name))) {
        const publicFile = resolve('public', file);
        digest.update(file);
        if (existsSync(publicFile)) {
          digest.update(readFileSync(publicFile));
        }
      }
      // Updating the worker implementation must also replace the previous cache.
      digest.update('public-shell-v2');
      const version = digest.digest('hex').slice(0, 16);
      const source = `/* Nasza Rodzina: public application files only. */
const CACHE_PREFIX = 'nr-public-shell-';
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(version)};
const BASE = new URL('./', self.location.href);
const SHELL = new URL('index.html', BASE).href;
const FILES = ${JSON.stringify(files)}.map(path => new URL(path, BASE).href);
const PUBLIC_URLS = new Set(FILES);

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(
    FILES.map(url => new Request(url, { cache: 'reload' }))
  )));
});

self.addEventListener('activate', event => {
  event.waitUntil(Promise.all([
    caches.keys().then(keys => Promise.all(keys.filter(key =>
      key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME
    ).map(key => caches.delete(key)))),
    self.clients.claim(),
  ]));
});

self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== BASE.origin) return;
  // API, Firebase, documents and every unlisted URL use the browser network directly.
  if (PUBLIC_URLS.has(url.href)) {
    event.respondWith(caches.open(CACHE_NAME).then(cache =>
      cache.match(request).then(cached => cached || fetch(request))
    ));
    return;
  }
  if (request.mode === 'navigate' && url.pathname === BASE.pathname) {
    // Do not store navigation responses; only the build's static index is available offline.
    event.respondWith(fetch(request).catch(async () => {
      const cache = await caches.open(CACHE_NAME);
      return (await cache.match(SHELL)) || Response.error();
    }));
  }
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

export default defineConfig({
  base: '/',
  plugins: [react(), publicShellWorker()],
});
