import { onAuthStateChanged, User } from 'firebase/auth';
import { auth } from './firebase';
import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Home,CalendarDays,CheckSquare,ShoppingCart,MessageCircle,Heart,GraduationCap,Users,Settings,Plus,Bell,CloudSun}from'lucide-react';import'./style.css';
const tabs=[['Start',Home],['Kalendarz',CalendarDays],['Zadania',CheckSquare],['Zakupy',ShoppingCart],['Czat',MessageCircle],['Zdrowie',Heart],['Szkoła',GraduationCap],['Rodzina',Users],['Ustawienia',Settings]] as const;
const people=[['Sebastian','Tata','S'],['Dominika','Mama','D'],['Paweł','Syn','P'],['Nikodem','Syn','N'],['Layla','Córka','L']];
function Card({title,children}:{title:string,children:React.ReactNode}){return <section className="card"><h3>{title}</h3>{children}</section>}
function App(){const[tab,setTab]=useState('Start');return <div className="app"><aside><div className="logo">🏠 <b>Nasza<br/>Rodzina</b></div>{tabs.map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)}><I size={20}/><span>{n}</span></button>)}</aside><main><header><div className="people">{people.map(([n,r,l])=><div className="person"><i>{l}</i><div><b>{n}</b><small>{r}</small></div></div>)}</div><Bell/></header><div className="mobileTitle"><b>🏠 Nasza Rodzina</b><Bell size={20}/></div>{tab==='Start'?<Start/>:<Module name={tab}/>}</main><nav>{tabs.slice(0,5).map(([n,I])=><button className={tab===n?'sel':''} onClick={()=>setTab(n)}><I/><small>{n}</small></button>)}<button onClick={()=>setTab('Ustawienia')}><Settings/><small>Więcej</small></button></nav></div>}
function Start(){return <><div className="hero"><div><small>Niedziela, 27 września</small><h1>Dzień dobry, Sebastian!</h1><p>Oto co dzieje się dziś w Waszej rodzinie.</p></div><div className="weather"><CloudSun/> <b>Kołobrzeg<br/><strong>18°C</strong></b></div></div><div className="grid"><Card title="📅 Dzisiaj w rodzinie"><p>08:00 • Paweł — szkoła</p><p>08:00 • Nikodem — szkoła</p><p>13:00 • Sebastian — dyżur</p></Card><Card title="✅ Zadania na dziś"><p>☑ Strój na WF — Paweł</p><p>□ Zeszyt do matematyki</p><p>□ Przygotować drugie śniadanie</p></Card><Card title="🛒 Lista zakupów"><p>□ Mleko</p><p>☑ Chleb</p><p>□ Banany</p></Card><Card title="🎒 Szkoła — Paweł"><div className="vulcan"><b>VULCAN</b><span>● Połączono</span></div><p>🔔 Zmiana planu lekcji</p><p>✉️ Nowa wiadomość od wychowawcy</p></Card><Card title="❤️ Zdrowie"><p>Layla — szczepienie • za 2 dni</p><p>Dominika — wizyta kontrolna • za 7 dni</p></Card><Card title="👨‍👩‍👧‍👦 Rodzina"><p>🎂 Roczek Layli — 10.10</p><p>❤️ Rocznica ślubu — 06.09</p></Card></div><button className="fab"><Plus/> Dodaj</button></>}
function Module({name}:{name:string}){const map:any={Kalendarz:'Wspólny kalendarz rodziny',Zadania:'Zadania rodzinne',Zakupy:'Wspólne listy zakupów',Czat:'Rodzinny czat',Zdrowie:'Historia zdrowia rodziny',Szkoła:'Szkoła i VULCAN',Rodzina:'Profile naszej rodziny',Ustawienia:'Ustawienia aplikacji'};return <><div className="moduleHead"><h1>{name}</h1><p>{map[name]}</p></div><div className="grid"><Card title="Pierwsza wersja modułu"><p>Ten ekran jest już częścią działającego szkieletu aplikacji.</p><p>W kolejnych etapach podłączymy tutaj dane z Firebase i funkcje zatwierdzone w projekcie.</p></Card>{name==='Szkoła'&&<Card title="VULCAN"><div className="vulcan"><b>VULCAN</b><span>Przygotowane do integracji</span></div><button className="primary">Otwórz VULCAN</button></Card>}{name==='Rodzina'&&<Card title="Członkowie rodziny">{people.map(p=><p>👤 {p[0]} — {p[1]}</p>)}</Card>}</div></>};createRoot(document.getElementById('root')!).render(<App/>);
